name: Release
on: 
  workflow_dispatch:
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-northeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Cloudformation Deploy
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: msgolf-hp-resources
          template: template.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            SSRFunctionDomainName=${{ secrets.SSRFunctionDomainName }},
            AcmId=${{ secrets.AcmId }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build
      - name: Serverless Deploy
        run: npx serverless deploy
      - name: Sync S3
        run: aws s3 sync .output/public/ s3://msgolf-hp-static/ --delete
